# -*- coding: utf-8 -*-
"""TeamSerine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdDbJCRDf5_g_nJSxIkaiG1BJ60hgGm-
"""

#import the pandas library
import pandas as pd

# Your sheet ID from the URL
sheet_id = "1A2luZe--pPmujc65jPZe-DjvoTeCJPsrtUknIPcIUq4"
sheet_name = "TeamSerine"
# Proper export link for CSV format
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

df = pd.read_csv(url)
print(df.head())

# Function to print one person's details
def show_person(name):
    person = df[df["Name"].str.lower() == name.lower()]  # case-insensitive match
    if person.empty:
        print(f"No match found for '{name}'.")
        return
    row = person.iloc[0]
    print(f"Name: {row['Name']}")
    print(f"Slack Username: {row['Slack UserName']}")
    print(f"Country: {row['Country']}")
    print(f"Hobby: {row['Hobby']}")
    print(f"Affiliations: {row['Affiliations']}")
    print(f"Favorite Gene & Sequence: {row['Favorite Gene & Sequence']}")

# Print Details
show_person("Abdulsalam RA")